namespace MLB;

table BallBounceDataWire {
  speed: float;
  endSpeed: float;

  startX: float;
  startY: float;
  startZ: float;

  endX: float;
  endY: float;
  endZ: float;

  startTime: float;
  endTime: float;
  landingTime: float;

  projectedX: float;
  projectedY: float;
  projectedZ: float;

  polynomialX1: float;
  polynomialX2: float;
  polynomialX3: float;

  polynomialY1: float;
  polynomialY2: float;
  polynomialY3: float;

  polynomialZ1: float;
  polynomialZ2: float;
  polynomialZ3: float;
}

table BallHitDataWire {
  speed: float;
  angle: float;
  direction: float;
  distance: float;
  actualDistance: float;

  actualX: float;
  actualY: float;
  actualZ: float;

  projectedX: float;
  projectedY: float;
  projectedZ: float;

  startTime: float;
  endTime: float;
  landingTime: float;

  polynomialX1: float;
  polynomialX2: float;
  polynomialX3: float;
  polynomialX4: float;
  polynomialX5: float;
  polynomialX6: float;
  polynomialX7: float;
  polynomialX8: float;
  polynomialX9: float;

  polynomialY1: float;
  polynomialY2: float;
  polynomialY3: float;
  polynomialY4: float;
  polynomialY5: float;
  polynomialY6: float;
  polynomialY7: float;
  polynomialY8: float;
  polynomialY9: float;

  polynomialZ1: float;
  polynomialZ2: float;
  polynomialZ3: float;
  polynomialZ4: float;
  polynomialZ5: float;
  polynomialZ6: float;
  polynomialZ7: float;
  polynomialZ8: float;
  polynomialZ9: float;
}

table BallHitLaunchWire {
  speed:float;
  angle:float;
  direction:float;
}

table BallHitRefinedWire {
  launchSpinRate: float;
  launchSpinAxis: float;
  apexX: float;
  apexY: float;
  apexZ: float;
}

table Vec3 {
  x: float;
  y: float;
  z: float;
}

table BallPitchTrajectoryDataWire {
  verticalBreak: float;
  verticalBreakInduced: float;
  horizontalBreak: float;

  horizontalApproachAngle: float;
  verticalApproachAngle: float;

  zoneSpeed: float;
  zoneTime: float;

  location: Vec3;

  trajectoryPolynomialX: Vec3;
  trajectoryPolynomialY: Vec3;
  trajectoryPolynomialZ: Vec3;
}

table BallPitchDataWire {
  speed: float;

  szTop: float;
  szBot: float;

  pitchType: string;
  type: string;

  releaseData: Vec3;
  trajectoryData: BallPitchTrajectoryDataWire;
}

table BallPitchRefinedWire {
  szTop: float;
  szBot: float;

  spinRate: float;
  spinAxis: float;

  extension: float;
  perceivedSpeed: float;

  x: float;
  y: float;
  z: float;
}

table BallThrowData {
  speed: float;
  endSpeed: float;
  startX: float;
  startY: float;
  startZ: float;
  endX: float;
  endY: float;
  endZ: float;
  startTime: float;
  endTime: float;
  landingTime: float;

  polynomialX1: float;
  polynomialX2: float;
  polynomialX3: float;

  polynomialY1: float;
  polynomialY2: float;
  polynomialY3: float;

  polynomialZ1: float;
  polynomialZ2: float;
  polynomialZ3: float;

  projectedX: float;
  projectedY: float;
  projectedZ: float;
}

// -----------------------------
// ENUM (discriminator for union)
// -----------------------------
enum BallPolynomialDataType : byte {
  NONE = 0,
  BallBounceDataWire = 1,
  BallHitDataWire = 2,
  BallHitLaunchWire = 3,
  BallHitRefinedWire = 4,
  BallPitchDataWire = 5,
  BallPitchRefinedWire = 6,
  BallThrowData = 7,
  BallPickOffDataWire = 8,
  BallPitchReleasePointWire = 9,
  BallPitchSpinWire = 10
}

table BallPickOffDataWire {
  predictedLandingY:float;
  predictedLandingZ:float;
  predictedLandingTime:float;
  predictedLandingX:float;

  speed:float;

  polynomialX2:float;
  polynomialY1:float;
  polynomialX3:float;
  polynomialY2:float;
  polynomialZ1:float;
  polynomialY3:float;
  polynomialZ2:float;
  polynomialZ3:float;

  endZ:float;
  endX:float;
  endY:float;

  venueId:string;

  endTime:float;
  publishTimestamp:string;

  polynomialX1:float;

  startX:float;
  startZ:float;
  endSpeed:float;
  startY:float;
}

table BallPitchReleasePointWire {
  extension: float;
  releaseTimestamp: string;
  publishTimestamp: string;

  releaseSpeed: float;
  effectiveVelocity: float;

  venueId: string;

  releasePosition: Vec3;

  x: float;
  y: float;
  z: float;
}

table BallPitchSpinWire {
  actualFrameRate: float;
  frame0Time: ulong;

  publishTimestamp: string;
  venueId: string;

  spinRate: float;
  spinAxis: float;
  spinReducedConfidence: float;

  spinVector: Vec3;

  x: float;
  y: float;
  z: float;

  xx: float;
  xy: float;
  xz: float;

  yx: float;
  yy: float;
  yz: float;

  zx: float;
  zy: float;
  zz: float;
}

// -----------------------------
// UNION
// -----------------------------
union BallPolynomialDataWire {
  BallBounceDataWire,
  BallHitDataWire,
  BallHitLaunchWire,
  BallHitRefinedWire,
  BallPitchDataWire,
  BallPitchRefinedWire,
  BallThrowData,
  BallPickOffDataWire,
  BallPitchReleasePointWire,
  BallPitchSpinWire
}

// -----------------------------
// TABLE
// -----------------------------
table BallPolynomialWire {
  id:string;
  timestamp:string;
  dtype:BallPolynomialDataType;
  data:BallPolynomialDataWire;
}

root_type BallPolynomialWire;