# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ABSEventDataWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ABSEventDataWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsABSEventDataWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ABSEventDataWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ABSEventDataWire
    def Depth(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ABSEventDataWire
    def Width(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ABSEventDataWire
    def Top(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ABSEventDataWire
    def Bottom(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ABSEventDataWire
    def BallIntersection(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from MLB.Vec3Wire import Vec3Wire
            obj = Vec3Wire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ABSEventDataWire
    def BallDiam(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def ABSEventDataWireStart(builder): builder.StartObject(6)
def Start(builder):
    return ABSEventDataWireStart(builder)
def ABSEventDataWireAddDepth(builder, depth): builder.PrependFloat32Slot(0, depth, 0.0)
def AddDepth(builder, depth):
    return ABSEventDataWireAddDepth(builder, depth)
def ABSEventDataWireAddWidth(builder, width): builder.PrependFloat32Slot(1, width, 0.0)
def AddWidth(builder, width):
    return ABSEventDataWireAddWidth(builder, width)
def ABSEventDataWireAddTop(builder, top): builder.PrependFloat32Slot(2, top, 0.0)
def AddTop(builder, top):
    return ABSEventDataWireAddTop(builder, top)
def ABSEventDataWireAddBottom(builder, bottom): builder.PrependFloat32Slot(3, bottom, 0.0)
def AddBottom(builder, bottom):
    return ABSEventDataWireAddBottom(builder, bottom)
def ABSEventDataWireAddBallIntersection(builder, ballIntersection): builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(ballIntersection), 0)
def AddBallIntersection(builder, ballIntersection):
    return ABSEventDataWireAddBallIntersection(builder, ballIntersection)
def ABSEventDataWireAddBallDiam(builder, ballDiam): builder.PrependFloat32Slot(5, ballDiam, 0.0)
def AddBallDiam(builder, ballDiam):
    return ABSEventDataWireAddBallDiam(builder, ballDiam)
def ABSEventDataWireEnd(builder): return builder.EndObject()
def End(builder):
    return ABSEventDataWireEnd(builder)