# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ActorPoseWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ActorPoseWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsActorPoseWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ActorPoseWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ActorPoseWire
    def Uid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ActorPoseWire
    def RootPos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from MLB.Vec3Wire import Vec3Wire
            obj = Vec3Wire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ActorPoseWire
    def PackedQuats(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ActorPoseWire
    def PackedQuatsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # ActorPoseWire
    def PackedQuatsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ActorPoseWire
    def PackedQuatsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # ActorPoseWire
    def NodeIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2))
        return 0

    # ActorPoseWire
    def NodeIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint16Flags, o)
        return 0

    # ActorPoseWire
    def NodeIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ActorPoseWire
    def NodeIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # ActorPoseWire
    def Ground(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ActorPoseWire
    def Apex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ActorPoseWire
    def Scale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ActorPoseWire
    def BatRootPos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = o + self._tab.Pos
            from MLB.Vec3Wire import Vec3Wire
            obj = Vec3Wire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ActorPoseWireStart(builder): builder.StartObject(8)
def Start(builder):
    return ActorPoseWireStart(builder)
def ActorPoseWireAddUid(builder, uid): builder.PrependUint32Slot(0, uid, 0)
def AddUid(builder, uid):
    return ActorPoseWireAddUid(builder, uid)
def ActorPoseWireAddRootPos(builder, rootPos): builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(rootPos), 0)
def AddRootPos(builder, rootPos):
    return ActorPoseWireAddRootPos(builder, rootPos)
def ActorPoseWireAddPackedQuats(builder, packedQuats): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(packedQuats), 0)
def AddPackedQuats(builder, packedQuats):
    return ActorPoseWireAddPackedQuats(builder, packedQuats)
def ActorPoseWireStartPackedQuatsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartPackedQuatsVector(builder, numElems):
    return ActorPoseWireStartPackedQuatsVector(builder, numElems)
def ActorPoseWireAddNodeIds(builder, nodeIds): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(nodeIds), 0)
def AddNodeIds(builder, nodeIds):
    return ActorPoseWireAddNodeIds(builder, nodeIds)
def ActorPoseWireStartNodeIdsVector(builder, numElems): return builder.StartVector(2, numElems, 2)
def StartNodeIdsVector(builder, numElems):
    return ActorPoseWireStartNodeIdsVector(builder, numElems)
def ActorPoseWireAddGround(builder, ground): builder.PrependFloat32Slot(4, ground, 0.0)
def AddGround(builder, ground):
    return ActorPoseWireAddGround(builder, ground)
def ActorPoseWireAddApex(builder, apex): builder.PrependFloat32Slot(5, apex, 0.0)
def AddApex(builder, apex):
    return ActorPoseWireAddApex(builder, apex)
def ActorPoseWireAddScale(builder, scale): builder.PrependFloat32Slot(6, scale, 0.0)
def AddScale(builder, scale):
    return ActorPoseWireAddScale(builder, scale)
def ActorPoseWireAddBatRootPos(builder, batRootPos): builder.PrependStructSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(batRootPos), 0)
def AddBatRootPos(builder, batRootPos):
    return ActorPoseWireAddBatRootPos(builder, batRootPos)
def ActorPoseWireEnd(builder): return builder.EndObject()
def End(builder):
    return ActorPoseWireEnd(builder)