# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BallThrowData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BallThrowData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBallThrowData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BallThrowData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BallThrowData
    def Speed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallThrowData
    def EndSpeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallThrowData
    def StartX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallThrowData
    def StartY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallThrowData
    def StartZ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallThrowData
    def EndX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallThrowData
    def EndY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallThrowData
    def EndZ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallThrowData
    def ProjectedX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallThrowData
    def ProjectedY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallThrowData
    def ProjectedZ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallThrowData
    def PolynomialX1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallThrowData
    def PolynomialX2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallThrowData
    def PolynomialX3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallThrowData
    def PolynomialY1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallThrowData
    def PolynomialY2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallThrowData
    def PolynomialY3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallThrowData
    def PolynomialZ1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallThrowData
    def PolynomialZ2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallThrowData
    def PolynomialZ3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallThrowData
    def StartTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallThrowData
    def EndTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallThrowData
    def LandingTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def BallThrowDataStart(builder): builder.StartObject(23)
def Start(builder):
    return BallThrowDataStart(builder)
def BallThrowDataAddSpeed(builder, speed): builder.PrependFloat32Slot(0, speed, 0.0)
def AddSpeed(builder, speed):
    return BallThrowDataAddSpeed(builder, speed)
def BallThrowDataAddEndSpeed(builder, endSpeed): builder.PrependFloat32Slot(1, endSpeed, 0.0)
def AddEndSpeed(builder, endSpeed):
    return BallThrowDataAddEndSpeed(builder, endSpeed)
def BallThrowDataAddStartX(builder, startX): builder.PrependFloat32Slot(2, startX, 0.0)
def AddStartX(builder, startX):
    return BallThrowDataAddStartX(builder, startX)
def BallThrowDataAddStartY(builder, startY): builder.PrependFloat32Slot(3, startY, 0.0)
def AddStartY(builder, startY):
    return BallThrowDataAddStartY(builder, startY)
def BallThrowDataAddStartZ(builder, startZ): builder.PrependFloat32Slot(4, startZ, 0.0)
def AddStartZ(builder, startZ):
    return BallThrowDataAddStartZ(builder, startZ)
def BallThrowDataAddEndX(builder, endX): builder.PrependFloat32Slot(5, endX, 0.0)
def AddEndX(builder, endX):
    return BallThrowDataAddEndX(builder, endX)
def BallThrowDataAddEndY(builder, endY): builder.PrependFloat32Slot(6, endY, 0.0)
def AddEndY(builder, endY):
    return BallThrowDataAddEndY(builder, endY)
def BallThrowDataAddEndZ(builder, endZ): builder.PrependFloat32Slot(7, endZ, 0.0)
def AddEndZ(builder, endZ):
    return BallThrowDataAddEndZ(builder, endZ)
def BallThrowDataAddProjectedX(builder, projectedX): builder.PrependFloat32Slot(8, projectedX, 0.0)
def AddProjectedX(builder, projectedX):
    return BallThrowDataAddProjectedX(builder, projectedX)
def BallThrowDataAddProjectedY(builder, projectedY): builder.PrependFloat32Slot(9, projectedY, 0.0)
def AddProjectedY(builder, projectedY):
    return BallThrowDataAddProjectedY(builder, projectedY)
def BallThrowDataAddProjectedZ(builder, projectedZ): builder.PrependFloat32Slot(10, projectedZ, 0.0)
def AddProjectedZ(builder, projectedZ):
    return BallThrowDataAddProjectedZ(builder, projectedZ)
def BallThrowDataAddPolynomialX1(builder, polynomialX1): builder.PrependFloat32Slot(11, polynomialX1, 0.0)
def AddPolynomialX1(builder, polynomialX1):
    return BallThrowDataAddPolynomialX1(builder, polynomialX1)
def BallThrowDataAddPolynomialX2(builder, polynomialX2): builder.PrependFloat32Slot(12, polynomialX2, 0.0)
def AddPolynomialX2(builder, polynomialX2):
    return BallThrowDataAddPolynomialX2(builder, polynomialX2)
def BallThrowDataAddPolynomialX3(builder, polynomialX3): builder.PrependFloat32Slot(13, polynomialX3, 0.0)
def AddPolynomialX3(builder, polynomialX3):
    return BallThrowDataAddPolynomialX3(builder, polynomialX3)
def BallThrowDataAddPolynomialY1(builder, polynomialY1): builder.PrependFloat32Slot(14, polynomialY1, 0.0)
def AddPolynomialY1(builder, polynomialY1):
    return BallThrowDataAddPolynomialY1(builder, polynomialY1)
def BallThrowDataAddPolynomialY2(builder, polynomialY2): builder.PrependFloat32Slot(15, polynomialY2, 0.0)
def AddPolynomialY2(builder, polynomialY2):
    return BallThrowDataAddPolynomialY2(builder, polynomialY2)
def BallThrowDataAddPolynomialY3(builder, polynomialY3): builder.PrependFloat32Slot(16, polynomialY3, 0.0)
def AddPolynomialY3(builder, polynomialY3):
    return BallThrowDataAddPolynomialY3(builder, polynomialY3)
def BallThrowDataAddPolynomialZ1(builder, polynomialZ1): builder.PrependFloat32Slot(17, polynomialZ1, 0.0)
def AddPolynomialZ1(builder, polynomialZ1):
    return BallThrowDataAddPolynomialZ1(builder, polynomialZ1)
def BallThrowDataAddPolynomialZ2(builder, polynomialZ2): builder.PrependFloat32Slot(18, polynomialZ2, 0.0)
def AddPolynomialZ2(builder, polynomialZ2):
    return BallThrowDataAddPolynomialZ2(builder, polynomialZ2)
def BallThrowDataAddPolynomialZ3(builder, polynomialZ3): builder.PrependFloat32Slot(19, polynomialZ3, 0.0)
def AddPolynomialZ3(builder, polynomialZ3):
    return BallThrowDataAddPolynomialZ3(builder, polynomialZ3)
def BallThrowDataAddStartTime(builder, startTime): builder.PrependFloat32Slot(20, startTime, 0.0)
def AddStartTime(builder, startTime):
    return BallThrowDataAddStartTime(builder, startTime)
def BallThrowDataAddEndTime(builder, endTime): builder.PrependFloat32Slot(21, endTime, 0.0)
def AddEndTime(builder, endTime):
    return BallThrowDataAddEndTime(builder, endTime)
def BallThrowDataAddLandingTime(builder, landingTime): builder.PrependFloat32Slot(22, landingTime, 0.0)
def AddLandingTime(builder, landingTime):
    return BallThrowDataAddLandingTime(builder, landingTime)
def BallThrowDataEnd(builder): return builder.EndObject()
def End(builder):
    return BallThrowDataEnd(builder)