# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BallPitchSpinWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BallPitchSpinWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBallPitchSpinWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BallPitchSpinWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BallPitchSpinWire
    def ActualFrameRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchSpinWire
    def Xx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchSpinWire
    def Yy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchSpinWire
    def Zz(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchSpinWire
    def Xy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchSpinWire
    def Yz(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchSpinWire
    def Xz(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchSpinWire
    def SpinReducedConfidence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchSpinWire
    def SpinRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchSpinWire
    def PublishTimestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BallPitchSpinWire
    def SpinAxis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchSpinWire
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchSpinWire
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchSpinWire
    def Frame0time(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchSpinWire
    def Z(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchSpinWire
    def SpinVector(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            x = o + self._tab.Pos
            from MLB.Vec3Wire import Vec3Wire
            obj = Vec3Wire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BallPitchSpinWire
    def VenueId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BallPitchSpinWire
    def Zx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchSpinWire
    def Yx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchSpinWire
    def Zy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def BallPitchSpinWireStart(builder): builder.StartObject(20)
def Start(builder):
    return BallPitchSpinWireStart(builder)
def BallPitchSpinWireAddActualFrameRate(builder, actualFrameRate): builder.PrependFloat32Slot(0, actualFrameRate, 0.0)
def AddActualFrameRate(builder, actualFrameRate):
    return BallPitchSpinWireAddActualFrameRate(builder, actualFrameRate)
def BallPitchSpinWireAddXx(builder, xx): builder.PrependFloat32Slot(1, xx, 0.0)
def AddXx(builder, xx):
    return BallPitchSpinWireAddXx(builder, xx)
def BallPitchSpinWireAddYy(builder, yy): builder.PrependFloat32Slot(2, yy, 0.0)
def AddYy(builder, yy):
    return BallPitchSpinWireAddYy(builder, yy)
def BallPitchSpinWireAddZz(builder, zz): builder.PrependFloat32Slot(3, zz, 0.0)
def AddZz(builder, zz):
    return BallPitchSpinWireAddZz(builder, zz)
def BallPitchSpinWireAddXy(builder, xy): builder.PrependFloat32Slot(4, xy, 0.0)
def AddXy(builder, xy):
    return BallPitchSpinWireAddXy(builder, xy)
def BallPitchSpinWireAddYz(builder, yz): builder.PrependFloat32Slot(5, yz, 0.0)
def AddYz(builder, yz):
    return BallPitchSpinWireAddYz(builder, yz)
def BallPitchSpinWireAddXz(builder, xz): builder.PrependFloat32Slot(6, xz, 0.0)
def AddXz(builder, xz):
    return BallPitchSpinWireAddXz(builder, xz)
def BallPitchSpinWireAddSpinReducedConfidence(builder, spinReducedConfidence): builder.PrependFloat32Slot(7, spinReducedConfidence, 0.0)
def AddSpinReducedConfidence(builder, spinReducedConfidence):
    return BallPitchSpinWireAddSpinReducedConfidence(builder, spinReducedConfidence)
def BallPitchSpinWireAddSpinRate(builder, spinRate): builder.PrependFloat32Slot(8, spinRate, 0.0)
def AddSpinRate(builder, spinRate):
    return BallPitchSpinWireAddSpinRate(builder, spinRate)
def BallPitchSpinWireAddPublishTimestamp(builder, publishTimestamp): builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(publishTimestamp), 0)
def AddPublishTimestamp(builder, publishTimestamp):
    return BallPitchSpinWireAddPublishTimestamp(builder, publishTimestamp)
def BallPitchSpinWireAddSpinAxis(builder, spinAxis): builder.PrependFloat32Slot(10, spinAxis, 0.0)
def AddSpinAxis(builder, spinAxis):
    return BallPitchSpinWireAddSpinAxis(builder, spinAxis)
def BallPitchSpinWireAddX(builder, x): builder.PrependFloat32Slot(11, x, 0.0)
def AddX(builder, x):
    return BallPitchSpinWireAddX(builder, x)
def BallPitchSpinWireAddY(builder, y): builder.PrependFloat32Slot(12, y, 0.0)
def AddY(builder, y):
    return BallPitchSpinWireAddY(builder, y)
def BallPitchSpinWireAddFrame0time(builder, frame0time): builder.PrependFloat32Slot(13, frame0time, 0.0)
def AddFrame0time(builder, frame0time):
    return BallPitchSpinWireAddFrame0time(builder, frame0time)
def BallPitchSpinWireAddZ(builder, z): builder.PrependFloat32Slot(14, z, 0.0)
def AddZ(builder, z):
    return BallPitchSpinWireAddZ(builder, z)
def BallPitchSpinWireAddSpinVector(builder, spinVector): builder.PrependStructSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(spinVector), 0)
def AddSpinVector(builder, spinVector):
    return BallPitchSpinWireAddSpinVector(builder, spinVector)
def BallPitchSpinWireAddVenueId(builder, venueId): builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(venueId), 0)
def AddVenueId(builder, venueId):
    return BallPitchSpinWireAddVenueId(builder, venueId)
def BallPitchSpinWireAddZx(builder, zx): builder.PrependFloat32Slot(17, zx, 0.0)
def AddZx(builder, zx):
    return BallPitchSpinWireAddZx(builder, zx)
def BallPitchSpinWireAddYx(builder, yx): builder.PrependFloat32Slot(18, yx, 0.0)
def AddYx(builder, yx):
    return BallPitchSpinWireAddYx(builder, yx)
def BallPitchSpinWireAddZy(builder, zy): builder.PrependFloat32Slot(19, zy, 0.0)
def AddZy(builder, zy):
    return BallPitchSpinWireAddZy(builder, zy)
def BallPitchSpinWireEnd(builder): return builder.EndObject()
def End(builder):
    return BallPitchSpinWireEnd(builder)