# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BallPitchTrajectoryDataWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BallPitchTrajectoryDataWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBallPitchTrajectoryDataWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BallPitchTrajectoryDataWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BallPitchTrajectoryDataWire
    def VerticalBreak(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchTrajectoryDataWire
    def VerticalBreakInduced(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchTrajectoryDataWire
    def HorizontalBreak(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchTrajectoryDataWire
    def HorizontalApproachAngle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchTrajectoryDataWire
    def VerticalApproachAngle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchTrajectoryDataWire
    def ZoneSpeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchTrajectoryDataWire
    def ZoneTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchTrajectoryDataWire
    def Location(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BallPitchTrajectoryDataWire
    def TrajectoryPolynomialX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BallPitchTrajectoryDataWire
    def TrajectoryPolynomialY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BallPitchTrajectoryDataWire
    def TrajectoryPolynomialZ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def BallPitchTrajectoryDataWireStart(builder):
    builder.StartObject(11)

def Start(builder):
    BallPitchTrajectoryDataWireStart(builder)

def BallPitchTrajectoryDataWireAddVerticalBreak(builder, verticalBreak):
    builder.PrependFloat32Slot(0, verticalBreak, 0.0)

def AddVerticalBreak(builder, verticalBreak):
    BallPitchTrajectoryDataWireAddVerticalBreak(builder, verticalBreak)

def BallPitchTrajectoryDataWireAddVerticalBreakInduced(builder, verticalBreakInduced):
    builder.PrependFloat32Slot(1, verticalBreakInduced, 0.0)

def AddVerticalBreakInduced(builder, verticalBreakInduced):
    BallPitchTrajectoryDataWireAddVerticalBreakInduced(builder, verticalBreakInduced)

def BallPitchTrajectoryDataWireAddHorizontalBreak(builder, horizontalBreak):
    builder.PrependFloat32Slot(2, horizontalBreak, 0.0)

def AddHorizontalBreak(builder, horizontalBreak):
    BallPitchTrajectoryDataWireAddHorizontalBreak(builder, horizontalBreak)

def BallPitchTrajectoryDataWireAddHorizontalApproachAngle(builder, horizontalApproachAngle):
    builder.PrependFloat32Slot(3, horizontalApproachAngle, 0.0)

def AddHorizontalApproachAngle(builder, horizontalApproachAngle):
    BallPitchTrajectoryDataWireAddHorizontalApproachAngle(builder, horizontalApproachAngle)

def BallPitchTrajectoryDataWireAddVerticalApproachAngle(builder, verticalApproachAngle):
    builder.PrependFloat32Slot(4, verticalApproachAngle, 0.0)

def AddVerticalApproachAngle(builder, verticalApproachAngle):
    BallPitchTrajectoryDataWireAddVerticalApproachAngle(builder, verticalApproachAngle)

def BallPitchTrajectoryDataWireAddZoneSpeed(builder, zoneSpeed):
    builder.PrependFloat32Slot(5, zoneSpeed, 0.0)

def AddZoneSpeed(builder, zoneSpeed):
    BallPitchTrajectoryDataWireAddZoneSpeed(builder, zoneSpeed)

def BallPitchTrajectoryDataWireAddZoneTime(builder, zoneTime):
    builder.PrependFloat32Slot(6, zoneTime, 0.0)

def AddZoneTime(builder, zoneTime):
    BallPitchTrajectoryDataWireAddZoneTime(builder, zoneTime)

def BallPitchTrajectoryDataWireAddLocation(builder, location):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(location), 0)

def AddLocation(builder, location):
    BallPitchTrajectoryDataWireAddLocation(builder, location)

def BallPitchTrajectoryDataWireAddTrajectoryPolynomialX(builder, trajectoryPolynomialX):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(trajectoryPolynomialX), 0)

def AddTrajectoryPolynomialX(builder, trajectoryPolynomialX):
    BallPitchTrajectoryDataWireAddTrajectoryPolynomialX(builder, trajectoryPolynomialX)

def BallPitchTrajectoryDataWireAddTrajectoryPolynomialY(builder, trajectoryPolynomialY):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(trajectoryPolynomialY), 0)

def AddTrajectoryPolynomialY(builder, trajectoryPolynomialY):
    BallPitchTrajectoryDataWireAddTrajectoryPolynomialY(builder, trajectoryPolynomialY)

def BallPitchTrajectoryDataWireAddTrajectoryPolynomialZ(builder, trajectoryPolynomialZ):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(trajectoryPolynomialZ), 0)

def AddTrajectoryPolynomialZ(builder, trajectoryPolynomialZ):
    BallPitchTrajectoryDataWireAddTrajectoryPolynomialZ(builder, trajectoryPolynomialZ)

def BallPitchTrajectoryDataWireEnd(builder):
    return builder.EndObject()

def End(builder):
    return BallPitchTrajectoryDataWireEnd(builder)
