# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BallPitchReleasePointWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BallPitchReleasePointWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBallPitchReleasePointWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BallPitchReleasePointWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BallPitchReleasePointWire
    def Extension(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchReleasePointWire
    def ReleaseTimestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BallPitchReleasePointWire
    def ReleasePosition(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from MLB.Vec3Wire import Vec3Wire
            obj = Vec3Wire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BallPitchReleasePointWire
    def PublishTimestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BallPitchReleasePointWire
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchReleasePointWire
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchReleasePointWire
    def EffectiveVelocity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchReleasePointWire
    def Z(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchReleasePointWire
    def ReleaseSpeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchReleasePointWire
    def VenueId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def BallPitchReleasePointWireStart(builder): builder.StartObject(10)
def Start(builder):
    return BallPitchReleasePointWireStart(builder)
def BallPitchReleasePointWireAddExtension(builder, extension): builder.PrependFloat32Slot(0, extension, 0.0)
def AddExtension(builder, extension):
    return BallPitchReleasePointWireAddExtension(builder, extension)
def BallPitchReleasePointWireAddReleaseTimestamp(builder, releaseTimestamp): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(releaseTimestamp), 0)
def AddReleaseTimestamp(builder, releaseTimestamp):
    return BallPitchReleasePointWireAddReleaseTimestamp(builder, releaseTimestamp)
def BallPitchReleasePointWireAddReleasePosition(builder, releasePosition): builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(releasePosition), 0)
def AddReleasePosition(builder, releasePosition):
    return BallPitchReleasePointWireAddReleasePosition(builder, releasePosition)
def BallPitchReleasePointWireAddPublishTimestamp(builder, publishTimestamp): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(publishTimestamp), 0)
def AddPublishTimestamp(builder, publishTimestamp):
    return BallPitchReleasePointWireAddPublishTimestamp(builder, publishTimestamp)
def BallPitchReleasePointWireAddX(builder, x): builder.PrependFloat32Slot(4, x, 0.0)
def AddX(builder, x):
    return BallPitchReleasePointWireAddX(builder, x)
def BallPitchReleasePointWireAddY(builder, y): builder.PrependFloat32Slot(5, y, 0.0)
def AddY(builder, y):
    return BallPitchReleasePointWireAddY(builder, y)
def BallPitchReleasePointWireAddEffectiveVelocity(builder, effectiveVelocity): builder.PrependFloat32Slot(6, effectiveVelocity, 0.0)
def AddEffectiveVelocity(builder, effectiveVelocity):
    return BallPitchReleasePointWireAddEffectiveVelocity(builder, effectiveVelocity)
def BallPitchReleasePointWireAddZ(builder, z): builder.PrependFloat32Slot(7, z, 0.0)
def AddZ(builder, z):
    return BallPitchReleasePointWireAddZ(builder, z)
def BallPitchReleasePointWireAddReleaseSpeed(builder, releaseSpeed): builder.PrependFloat32Slot(8, releaseSpeed, 0.0)
def AddReleaseSpeed(builder, releaseSpeed):
    return BallPitchReleasePointWireAddReleaseSpeed(builder, releaseSpeed)
def BallPitchReleasePointWireAddVenueId(builder, venueId): builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(venueId), 0)
def AddVenueId(builder, venueId):
    return BallPitchReleasePointWireAddVenueId(builder, venueId)
def BallPitchReleasePointWireEnd(builder): return builder.EndObject()
def End(builder):
    return BallPitchReleasePointWireEnd(builder)