# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BallPitchRefinedWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BallPitchRefinedWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBallPitchRefinedWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BallPitchRefinedWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BallPitchRefinedWire
    def SzTop(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchRefinedWire
    def SzBot(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchRefinedWire
    def SpinRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchRefinedWire
    def SpinAxis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchRefinedWire
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchRefinedWire
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchRefinedWire
    def Z(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchRefinedWire
    def Extension(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchRefinedWire
    def PerceivedSpeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def BallPitchRefinedWireStart(builder): builder.StartObject(9)
def Start(builder):
    return BallPitchRefinedWireStart(builder)
def BallPitchRefinedWireAddSzTop(builder, szTop): builder.PrependFloat32Slot(0, szTop, 0.0)
def AddSzTop(builder, szTop):
    return BallPitchRefinedWireAddSzTop(builder, szTop)
def BallPitchRefinedWireAddSzBot(builder, szBot): builder.PrependFloat32Slot(1, szBot, 0.0)
def AddSzBot(builder, szBot):
    return BallPitchRefinedWireAddSzBot(builder, szBot)
def BallPitchRefinedWireAddSpinRate(builder, spinRate): builder.PrependFloat32Slot(2, spinRate, 0.0)
def AddSpinRate(builder, spinRate):
    return BallPitchRefinedWireAddSpinRate(builder, spinRate)
def BallPitchRefinedWireAddSpinAxis(builder, spinAxis): builder.PrependFloat32Slot(3, spinAxis, 0.0)
def AddSpinAxis(builder, spinAxis):
    return BallPitchRefinedWireAddSpinAxis(builder, spinAxis)
def BallPitchRefinedWireAddX(builder, x): builder.PrependFloat32Slot(4, x, 0.0)
def AddX(builder, x):
    return BallPitchRefinedWireAddX(builder, x)
def BallPitchRefinedWireAddY(builder, y): builder.PrependFloat32Slot(5, y, 0.0)
def AddY(builder, y):
    return BallPitchRefinedWireAddY(builder, y)
def BallPitchRefinedWireAddZ(builder, z): builder.PrependFloat32Slot(6, z, 0.0)
def AddZ(builder, z):
    return BallPitchRefinedWireAddZ(builder, z)
def BallPitchRefinedWireAddExtension(builder, extension): builder.PrependFloat32Slot(7, extension, 0.0)
def AddExtension(builder, extension):
    return BallPitchRefinedWireAddExtension(builder, extension)
def BallPitchRefinedWireAddPerceivedSpeed(builder, perceivedSpeed): builder.PrependFloat32Slot(8, perceivedSpeed, 0.0)
def AddPerceivedSpeed(builder, perceivedSpeed):
    return BallPitchRefinedWireAddPerceivedSpeed(builder, perceivedSpeed)
def BallPitchRefinedWireEnd(builder): return builder.EndObject()
def End(builder):
    return BallPitchRefinedWireEnd(builder)