# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BallPitchDataWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BallPitchDataWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBallPitchDataWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BallPitchDataWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BallPitchDataWire
    def Speed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchDataWire
    def SzTop(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchDataWire
    def SzBot(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchDataWire
    def PitchType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BallPitchDataWire
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BallPitchDataWire
    def ReleaseData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BallPitchDataWire
    def TrajectoryData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from BallPitchTrajectoryDataWire import BallPitchTrajectoryDataWire
            obj = BallPitchTrajectoryDataWire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def BallPitchDataWireStart(builder):
    builder.StartObject(7)

def Start(builder):
    BallPitchDataWireStart(builder)

def BallPitchDataWireAddSpeed(builder, speed):
    builder.PrependFloat32Slot(0, speed, 0.0)

def AddSpeed(builder, speed):
    BallPitchDataWireAddSpeed(builder, speed)

def BallPitchDataWireAddSzTop(builder, szTop):
    builder.PrependFloat32Slot(1, szTop, 0.0)

def AddSzTop(builder, szTop):
    BallPitchDataWireAddSzTop(builder, szTop)

def BallPitchDataWireAddSzBot(builder, szBot):
    builder.PrependFloat32Slot(2, szBot, 0.0)

def AddSzBot(builder, szBot):
    BallPitchDataWireAddSzBot(builder, szBot)

def BallPitchDataWireAddPitchType(builder, pitchType):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(pitchType), 0)

def AddPitchType(builder, pitchType):
    BallPitchDataWireAddPitchType(builder, pitchType)

def BallPitchDataWireAddType(builder, type):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(type), 0)

def AddType(builder, type):
    BallPitchDataWireAddType(builder, type)

def BallPitchDataWireAddReleaseData(builder, releaseData):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(releaseData), 0)

def AddReleaseData(builder, releaseData):
    BallPitchDataWireAddReleaseData(builder, releaseData)

def BallPitchDataWireAddTrajectoryData(builder, trajectoryData):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(trajectoryData), 0)

def AddTrajectoryData(builder, trajectoryData):
    BallPitchDataWireAddTrajectoryData(builder, trajectoryData)

def BallPitchDataWireEnd(builder):
    return builder.EndObject()

def End(builder):
    return BallPitchDataWireEnd(builder)
