# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BallPitchDataTrajectoryDataWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BallPitchDataTrajectoryDataWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBallPitchDataTrajectoryDataWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BallPitchDataTrajectoryDataWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BallPitchDataTrajectoryDataWire
    def VerticalBreak(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchDataTrajectoryDataWire
    def VerticalBreakInduced(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchDataTrajectoryDataWire
    def HorizontalBreak(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchDataTrajectoryDataWire
    def Location(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from MLB.Vec3Wire import Vec3Wire
            obj = Vec3Wire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BallPitchDataTrajectoryDataWire
    def ZoneSpeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchDataTrajectoryDataWire
    def VerticalApproachAngle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchDataTrajectoryDataWire
    def HorizontalApproachAngle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchDataTrajectoryDataWire
    def ZoneTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchDataTrajectoryDataWire
    def TrajectoryPolynomialX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = o + self._tab.Pos
            from MLB.Vec3Wire import Vec3Wire
            obj = Vec3Wire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BallPitchDataTrajectoryDataWire
    def TrajectoryPolynomialY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = o + self._tab.Pos
            from MLB.Vec3Wire import Vec3Wire
            obj = Vec3Wire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BallPitchDataTrajectoryDataWire
    def TrajectoryPolynomialZ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = o + self._tab.Pos
            from MLB.Vec3Wire import Vec3Wire
            obj = Vec3Wire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def BallPitchDataTrajectoryDataWireStart(builder): builder.StartObject(11)
def Start(builder):
    return BallPitchDataTrajectoryDataWireStart(builder)
def BallPitchDataTrajectoryDataWireAddVerticalBreak(builder, verticalBreak): builder.PrependFloat32Slot(0, verticalBreak, 0.0)
def AddVerticalBreak(builder, verticalBreak):
    return BallPitchDataTrajectoryDataWireAddVerticalBreak(builder, verticalBreak)
def BallPitchDataTrajectoryDataWireAddVerticalBreakInduced(builder, verticalBreakInduced): builder.PrependFloat32Slot(1, verticalBreakInduced, 0.0)
def AddVerticalBreakInduced(builder, verticalBreakInduced):
    return BallPitchDataTrajectoryDataWireAddVerticalBreakInduced(builder, verticalBreakInduced)
def BallPitchDataTrajectoryDataWireAddHorizontalBreak(builder, horizontalBreak): builder.PrependFloat32Slot(2, horizontalBreak, 0.0)
def AddHorizontalBreak(builder, horizontalBreak):
    return BallPitchDataTrajectoryDataWireAddHorizontalBreak(builder, horizontalBreak)
def BallPitchDataTrajectoryDataWireAddLocation(builder, location): builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(location), 0)
def AddLocation(builder, location):
    return BallPitchDataTrajectoryDataWireAddLocation(builder, location)
def BallPitchDataTrajectoryDataWireAddZoneSpeed(builder, zoneSpeed): builder.PrependFloat32Slot(4, zoneSpeed, 0.0)
def AddZoneSpeed(builder, zoneSpeed):
    return BallPitchDataTrajectoryDataWireAddZoneSpeed(builder, zoneSpeed)
def BallPitchDataTrajectoryDataWireAddVerticalApproachAngle(builder, verticalApproachAngle): builder.PrependFloat32Slot(5, verticalApproachAngle, 0.0)
def AddVerticalApproachAngle(builder, verticalApproachAngle):
    return BallPitchDataTrajectoryDataWireAddVerticalApproachAngle(builder, verticalApproachAngle)
def BallPitchDataTrajectoryDataWireAddHorizontalApproachAngle(builder, horizontalApproachAngle): builder.PrependFloat32Slot(6, horizontalApproachAngle, 0.0)
def AddHorizontalApproachAngle(builder, horizontalApproachAngle):
    return BallPitchDataTrajectoryDataWireAddHorizontalApproachAngle(builder, horizontalApproachAngle)
def BallPitchDataTrajectoryDataWireAddZoneTime(builder, zoneTime): builder.PrependFloat32Slot(7, zoneTime, 0.0)
def AddZoneTime(builder, zoneTime):
    return BallPitchDataTrajectoryDataWireAddZoneTime(builder, zoneTime)
def BallPitchDataTrajectoryDataWireAddTrajectoryPolynomialX(builder, trajectoryPolynomialX): builder.PrependStructSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(trajectoryPolynomialX), 0)
def AddTrajectoryPolynomialX(builder, trajectoryPolynomialX):
    return BallPitchDataTrajectoryDataWireAddTrajectoryPolynomialX(builder, trajectoryPolynomialX)
def BallPitchDataTrajectoryDataWireAddTrajectoryPolynomialY(builder, trajectoryPolynomialY): builder.PrependStructSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(trajectoryPolynomialY), 0)
def AddTrajectoryPolynomialY(builder, trajectoryPolynomialY):
    return BallPitchDataTrajectoryDataWireAddTrajectoryPolynomialY(builder, trajectoryPolynomialY)
def BallPitchDataTrajectoryDataWireAddTrajectoryPolynomialZ(builder, trajectoryPolynomialZ): builder.PrependStructSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(trajectoryPolynomialZ), 0)
def AddTrajectoryPolynomialZ(builder, trajectoryPolynomialZ):
    return BallPitchDataTrajectoryDataWireAddTrajectoryPolynomialZ(builder, trajectoryPolynomialZ)
def BallPitchDataTrajectoryDataWireEnd(builder): return builder.EndObject()
def End(builder):
    return BallPitchDataTrajectoryDataWireEnd(builder)