# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

class BallPolynomialDataWire(object):
    NONE = 0
    BallBounceDataWire = 1
    BallHitDataWire = 2
    BallHitLaunchWire = 3
    BallHitRefinedWire = 4
    BallPitchDataWire = 5
    BallPitchRefinedWire = 6
    BallThrowData = 7
    BallPickOffDataWire = 8
    BallPitchReleasePointWire = 9
    BallPitchSpinWire = 10
