# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BallPitchDataReleaseDataWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BallPitchDataReleaseDataWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBallPitchDataReleaseDataWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BallPitchDataReleaseDataWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BallPitchDataReleaseDataWire
    def Angle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallPitchDataReleaseDataWire
    def Direction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def BallPitchDataReleaseDataWireStart(builder): builder.StartObject(2)
def Start(builder):
    return BallPitchDataReleaseDataWireStart(builder)
def BallPitchDataReleaseDataWireAddAngle(builder, angle): builder.PrependFloat32Slot(0, angle, 0.0)
def AddAngle(builder, angle):
    return BallPitchDataReleaseDataWireAddAngle(builder, angle)
def BallPitchDataReleaseDataWireAddDirection(builder, direction): builder.PrependFloat32Slot(1, direction, 0.0)
def AddDirection(builder, direction):
    return BallPitchDataReleaseDataWireAddDirection(builder, direction)
def BallPitchDataReleaseDataWireEnd(builder): return builder.EndObject()
def End(builder):
    return BallPitchDataReleaseDataWireEnd(builder)