# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BallHitLaunchWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BallHitLaunchWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBallHitLaunchWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BallHitLaunchWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BallHitLaunchWire
    def Speed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallHitLaunchWire
    def Angle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallHitLaunchWire
    def Direction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def BallHitLaunchWireStart(builder):
    builder.StartObject(3)

def Start(builder):
    BallHitLaunchWireStart(builder)

def BallHitLaunchWireAddSpeed(builder, speed):
    builder.PrependFloat32Slot(0, speed, 0.0)

def AddSpeed(builder, speed):
    BallHitLaunchWireAddSpeed(builder, speed)

def BallHitLaunchWireAddAngle(builder, angle):
    builder.PrependFloat32Slot(1, angle, 0.0)

def AddAngle(builder, angle):
    BallHitLaunchWireAddAngle(builder, angle)

def BallHitLaunchWireAddDirection(builder, direction):
    builder.PrependFloat32Slot(2, direction, 0.0)

def AddDirection(builder, direction):
    BallHitLaunchWireAddDirection(builder, direction)

def BallHitLaunchWireEnd(builder):
    return builder.EndObject()

def End(builder):
    return BallHitLaunchWireEnd(builder)
