# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BallHitRefinedWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BallHitRefinedWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBallHitRefinedWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BallHitRefinedWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BallHitRefinedWire
    def LaunchSpinRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallHitRefinedWire
    def LaunchSpinAxis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallHitRefinedWire
    def ApexX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallHitRefinedWire
    def ApexY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BallHitRefinedWire
    def ApexZ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def BallHitRefinedWireStart(builder):
    builder.StartObject(5)

def Start(builder):
    BallHitRefinedWireStart(builder)

def BallHitRefinedWireAddLaunchSpinRate(builder, launchSpinRate):
    builder.PrependFloat32Slot(0, launchSpinRate, 0.0)

def AddLaunchSpinRate(builder, launchSpinRate):
    BallHitRefinedWireAddLaunchSpinRate(builder, launchSpinRate)

def BallHitRefinedWireAddLaunchSpinAxis(builder, launchSpinAxis):
    builder.PrependFloat32Slot(1, launchSpinAxis, 0.0)

def AddLaunchSpinAxis(builder, launchSpinAxis):
    BallHitRefinedWireAddLaunchSpinAxis(builder, launchSpinAxis)

def BallHitRefinedWireAddApexX(builder, apexX):
    builder.PrependFloat32Slot(2, apexX, 0.0)

def AddApexX(builder, apexX):
    BallHitRefinedWireAddApexX(builder, apexX)

def BallHitRefinedWireAddApexY(builder, apexY):
    builder.PrependFloat32Slot(3, apexY, 0.0)

def AddApexY(builder, apexY):
    BallHitRefinedWireAddApexY(builder, apexY)

def BallHitRefinedWireAddApexZ(builder, apexZ):
    builder.PrependFloat32Slot(4, apexZ, 0.0)

def AddApexZ(builder, apexZ):
    BallHitRefinedWireAddApexZ(builder, apexZ)

def BallHitRefinedWireEnd(builder):
    return builder.EndObject()

def End(builder):
    return BallHitRefinedWireEnd(builder)
