# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BatImpactEventDataWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BatImpactEventDataWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBatImpactEventDataWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BatImpactEventDataWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def BatImpactEventDataWireStart(builder): builder.StartObject(0)
def Start(builder):
    return BatImpactEventDataWireStart(builder)
def BatImpactEventDataWireEnd(builder): return builder.EndObject()
def End(builder):
    return BatImpactEventDataWireEnd(builder)