# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BattingOrderEventDataWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BattingOrderEventDataWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBattingOrderEventDataWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BattingOrderEventDataWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BattingOrderEventDataWire
    def Team(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # BattingOrderEventDataWire
    def PlayerIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # BattingOrderEventDataWire
    def PlayerIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # BattingOrderEventDataWire
    def PlayerIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BattingOrderEventDataWire
    def PlayerIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def BattingOrderEventDataWireStart(builder): builder.StartObject(2)
def Start(builder):
    return BattingOrderEventDataWireStart(builder)
def BattingOrderEventDataWireAddTeam(builder, team): builder.PrependInt8Slot(0, team, 0)
def AddTeam(builder, team):
    return BattingOrderEventDataWireAddTeam(builder, team)
def BattingOrderEventDataWireAddPlayerIds(builder, playerIds): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(playerIds), 0)
def AddPlayerIds(builder, playerIds):
    return BattingOrderEventDataWireAddPlayerIds(builder, playerIds)
def BattingOrderEventDataWireStartPlayerIdsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartPlayerIdsVector(builder, numElems):
    return BattingOrderEventDataWireStartPlayerIdsVector(builder, numElems)
def BattingOrderEventDataWireEnd(builder): return builder.EndObject()
def End(builder):
    return BattingOrderEventDataWireEnd(builder)