# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CountEventDataWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CountEventDataWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCountEventDataWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CountEventDataWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CountEventDataWire
    def Balls(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # CountEventDataWire
    def Strikes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # CountEventDataWire
    def Outs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def CountEventDataWireStart(builder): builder.StartObject(3)
def Start(builder):
    return CountEventDataWireStart(builder)
def CountEventDataWireAddBalls(builder, balls): builder.PrependUint16Slot(0, balls, 0)
def AddBalls(builder, balls):
    return CountEventDataWireAddBalls(builder, balls)
def CountEventDataWireAddStrikes(builder, strikes): builder.PrependUint16Slot(1, strikes, 0)
def AddStrikes(builder, strikes):
    return CountEventDataWireAddStrikes(builder, strikes)
def CountEventDataWireAddOuts(builder, outs): builder.PrependUint16Slot(2, outs, 0)
def AddOuts(builder, outs):
    return CountEventDataWireAddOuts(builder, outs)
def CountEventDataWireEnd(builder): return builder.EndObject()
def End(builder):
    return CountEventDataWireEnd(builder)