# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GameEventWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GameEventWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGameEventWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GameEventWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GameEventWire
    def DataType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # GameEventWire
    def Data(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

    # GameEventWire
    def Time(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # GameEventWire
    def IsKeyFramed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def GameEventWireStart(builder): builder.StartObject(4)
def Start(builder):
    return GameEventWireStart(builder)
def GameEventWireAddDataType(builder, dataType): builder.PrependUint8Slot(0, dataType, 0)
def AddDataType(builder, dataType):
    return GameEventWireAddDataType(builder, dataType)
def GameEventWireAddData(builder, data): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)
def AddData(builder, data):
    return GameEventWireAddData(builder, data)
def GameEventWireAddTime(builder, time): builder.PrependFloat64Slot(2, time, 0.0)
def AddTime(builder, time):
    return GameEventWireAddTime(builder, time)
def GameEventWireAddIsKeyFramed(builder, isKeyFramed): builder.PrependInt8Slot(3, isKeyFramed, 0)
def AddIsKeyFramed(builder, isKeyFramed):
    return GameEventWireAddIsKeyFramed(builder, isKeyFramed)
def GameEventWireEnd(builder): return builder.EndObject()
def End(builder):
    return GameEventWireEnd(builder)