# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

class GameEventDataWire(object):
    NONE = 0
    CountEventDataWire = 1
    TeamScoreEventDataWire = 2
    BattingOrderEventDataWire = 3
    LiveActionEventDataWire = 4
    InningEventDataWire = 5
    AtBatEventDataWire = 6
    PlayEventDataWire = 7
    HandedEventDataWire = 8
    PositionAssignmentEventDataWire = 9
    GumboTimecodeEventDataWire = 10
    StatusEventDataWire = 11
    BatImpactEventDataWire = 12
    HighFrequencyBatMarkerEventDataWire = 13
    ABSEventDataWire = 14
