# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GumboTimecodeEventDataWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GumboTimecodeEventDataWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGumboTimecodeEventDataWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GumboTimecodeEventDataWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GumboTimecodeEventDataWire
    def Timecode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def GumboTimecodeEventDataWireStart(builder): builder.StartObject(1)
def Start(builder):
    return GumboTimecodeEventDataWireStart(builder)
def GumboTimecodeEventDataWireAddTimecode(builder, timecode): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(timecode), 0)
def AddTimecode(builder, timecode):
    return GumboTimecodeEventDataWireAddTimecode(builder, timecode)
def GumboTimecodeEventDataWireEnd(builder): return builder.EndObject()
def End(builder):
    return GumboTimecodeEventDataWireEnd(builder)