# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HandedEventDataWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HandedEventDataWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHandedEventDataWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HandedEventDataWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HandedEventDataWire
    def Action(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # HandedEventDataWire
    def Side(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # HandedEventDataWire
    def ActorId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def HandedEventDataWireStart(builder): builder.StartObject(3)
def Start(builder):
    return HandedEventDataWireStart(builder)
def HandedEventDataWireAddAction(builder, action): builder.PrependInt8Slot(0, action, 0)
def AddAction(builder, action):
    return HandedEventDataWireAddAction(builder, action)
def HandedEventDataWireAddSide(builder, side): builder.PrependInt8Slot(1, side, 0)
def AddSide(builder, side):
    return HandedEventDataWireAddSide(builder, side)
def HandedEventDataWireAddActorId(builder, actorId): builder.PrependUint32Slot(2, actorId, 0)
def AddActorId(builder, actorId):
    return HandedEventDataWireAddActorId(builder, actorId)
def HandedEventDataWireEnd(builder): return builder.EndObject()
def End(builder):
    return HandedEventDataWireEnd(builder)