# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HighFrequencyBatMarkerEventDataWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HighFrequencyBatMarkerEventDataWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHighFrequencyBatMarkerEventDataWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HighFrequencyBatMarkerEventDataWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HighFrequencyBatMarkerEventDataWire
    def Action(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def HighFrequencyBatMarkerEventDataWireStart(builder): builder.StartObject(1)
def Start(builder):
    return HighFrequencyBatMarkerEventDataWireStart(builder)
def HighFrequencyBatMarkerEventDataWireAddAction(builder, action): builder.PrependInt8Slot(0, action, 0)
def AddAction(builder, action):
    return HighFrequencyBatMarkerEventDataWireAddAction(builder, action)
def HighFrequencyBatMarkerEventDataWireEnd(builder): return builder.EndObject()
def End(builder):
    return HighFrequencyBatMarkerEventDataWireEnd(builder)