# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InningEventDataWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InningEventDataWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInningEventDataWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InningEventDataWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InningEventDataWire
    def CurrentInning(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # InningEventDataWire
    def Action(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # InningEventDataWire
    def BattingTeamId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # InningEventDataWire
    def FieldingTeamId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def InningEventDataWireStart(builder): builder.StartObject(4)
def Start(builder):
    return InningEventDataWireStart(builder)
def InningEventDataWireAddCurrentInning(builder, currentInning): builder.PrependUint16Slot(0, currentInning, 0)
def AddCurrentInning(builder, currentInning):
    return InningEventDataWireAddCurrentInning(builder, currentInning)
def InningEventDataWireAddAction(builder, action): builder.PrependInt8Slot(1, action, 0)
def AddAction(builder, action):
    return InningEventDataWireAddAction(builder, action)
def InningEventDataWireAddBattingTeamId(builder, battingTeamId): builder.PrependUint16Slot(2, battingTeamId, 0)
def AddBattingTeamId(builder, battingTeamId):
    return InningEventDataWireAddBattingTeamId(builder, battingTeamId)
def InningEventDataWireAddFieldingTeamId(builder, fieldingTeamId): builder.PrependUint16Slot(3, fieldingTeamId, 0)
def AddFieldingTeamId(builder, fieldingTeamId):
    return InningEventDataWireAddFieldingTeamId(builder, fieldingTeamId)
def InningEventDataWireEnd(builder): return builder.EndObject()
def End(builder):
    return InningEventDataWireEnd(builder)