# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LiveActionEventDataWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LiveActionEventDataWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLiveActionEventDataWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LiveActionEventDataWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LiveActionEventDataWire
    def Mode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def LiveActionEventDataWireStart(builder): builder.StartObject(1)
def Start(builder):
    return LiveActionEventDataWireStart(builder)
def LiveActionEventDataWireAddMode(builder, mode): builder.PrependBoolSlot(0, mode, 0)
def AddMode(builder, mode):
    return LiveActionEventDataWireAddMode(builder, mode)
def LiveActionEventDataWireEnd(builder): return builder.EndObject()
def End(builder):
    return LiveActionEventDataWireEnd(builder)