# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PlayEventDataWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PlayEventDataWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPlayEventDataWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PlayEventDataWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PlayEventDataWire
    def Action(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # PlayEventDataWire
    def Index(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # PlayEventDataWire
    def PlayId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PlayEventDataWire
    def Strikezone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MLB.PlayEventWireStrikezone import PlayEventWireStrikezone
            obj = PlayEventWireStrikezone()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def PlayEventDataWireStart(builder): builder.StartObject(4)
def Start(builder):
    return PlayEventDataWireStart(builder)
def PlayEventDataWireAddAction(builder, action): builder.PrependInt8Slot(0, action, 0)
def AddAction(builder, action):
    return PlayEventDataWireAddAction(builder, action)
def PlayEventDataWireAddIndex(builder, index): builder.PrependUint16Slot(1, index, 0)
def AddIndex(builder, index):
    return PlayEventDataWireAddIndex(builder, index)
def PlayEventDataWireAddPlayId(builder, playId): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(playId), 0)
def AddPlayId(builder, playId):
    return PlayEventDataWireAddPlayId(builder, playId)
def PlayEventDataWireAddStrikezone(builder, strikezone): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(strikezone), 0)
def AddStrikezone(builder, strikezone):
    return PlayEventDataWireAddStrikezone(builder, strikezone)
def PlayEventDataWireEnd(builder): return builder.EndObject()
def End(builder):
    return PlayEventDataWireEnd(builder)