# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PlayEventWireStrikezone(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PlayEventWireStrikezone()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPlayEventWireStrikezone(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PlayEventWireStrikezone
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PlayEventWireStrikezone
    def Top(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # PlayEventWireStrikezone
    def Bottom(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # PlayEventWireStrikezone
    def Width(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # PlayEventWireStrikezone
    def Depth(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def PlayEventWireStrikezoneStart(builder):
    builder.StartObject(4)

def Start(builder):
    PlayEventWireStrikezoneStart(builder)

def PlayEventWireStrikezoneAddTop(builder, top):
    builder.PrependFloat32Slot(0, top, 0.0)

def AddTop(builder, top):
    PlayEventWireStrikezoneAddTop(builder, top)

def PlayEventWireStrikezoneAddBottom(builder, bottom):
    builder.PrependFloat32Slot(1, bottom, 0.0)

def AddBottom(builder, bottom):
    PlayEventWireStrikezoneAddBottom(builder, bottom)

def PlayEventWireStrikezoneAddWidth(builder, width):
    builder.PrependFloat32Slot(2, width, 0.0)

def AddWidth(builder, width):
    PlayEventWireStrikezoneAddWidth(builder, width)

def PlayEventWireStrikezoneAddDepth(builder, depth):
    builder.PrependFloat32Slot(3, depth, 0.0)

def AddDepth(builder, depth):
    PlayEventWireStrikezoneAddDepth(builder, depth)

def PlayEventWireStrikezoneEnd(builder):
    return builder.EndObject()

def End(builder):
    return PlayEventWireStrikezoneEnd(builder)
