# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PositionAssignmentEventDataWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PositionAssignmentEventDataWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPositionAssignmentEventDataWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PositionAssignmentEventDataWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PositionAssignmentEventDataWire
    def TrackUid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PositionAssignmentEventDataWire
    def NewPosition(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def PositionAssignmentEventDataWireStart(builder): builder.StartObject(2)
def Start(builder):
    return PositionAssignmentEventDataWireStart(builder)
def PositionAssignmentEventDataWireAddTrackUid(builder, trackUid): builder.PrependUint32Slot(0, trackUid, 0)
def AddTrackUid(builder, trackUid):
    return PositionAssignmentEventDataWireAddTrackUid(builder, trackUid)
def PositionAssignmentEventDataWireAddNewPosition(builder, newPosition): builder.PrependUint16Slot(1, newPosition, 0)
def AddNewPosition(builder, newPosition):
    return PositionAssignmentEventDataWireAddNewPosition(builder, newPosition)
def PositionAssignmentEventDataWireEnd(builder): return builder.EndObject()
def End(builder):
    return PositionAssignmentEventDataWireEnd(builder)