# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SkeletalPlayerWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SkeletalPlayerWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSkeletalPlayerWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SkeletalPlayerWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SkeletalPlayerWire
    def PositionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # SkeletalPlayerWire
    def TrackId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SkeletalPlayerWire
    def JointPositions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # SkeletalPlayerWire
    def JointPositionsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # SkeletalPlayerWire
    def JointPositionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SkeletalPlayerWire
    def JointPositionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # SkeletalPlayerWire
    def JointIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # SkeletalPlayerWire
    def JointIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # SkeletalPlayerWire
    def JointIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SkeletalPlayerWire
    def JointIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # SkeletalPlayerWire
    def PlayerId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SkeletalPlayerWire
    def JerseyNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SkeletalPlayerWire
    def RoleId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def SkeletalPlayerWireStart(builder): builder.StartObject(7)
def Start(builder):
    return SkeletalPlayerWireStart(builder)
def SkeletalPlayerWireAddPositionId(builder, positionId): builder.PrependUint16Slot(0, positionId, 0)
def AddPositionId(builder, positionId):
    return SkeletalPlayerWireAddPositionId(builder, positionId)
def SkeletalPlayerWireAddTrackId(builder, trackId): builder.PrependUint32Slot(1, trackId, 0)
def AddTrackId(builder, trackId):
    return SkeletalPlayerWireAddTrackId(builder, trackId)
def SkeletalPlayerWireAddJointPositions(builder, jointPositions): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(jointPositions), 0)
def AddJointPositions(builder, jointPositions):
    return SkeletalPlayerWireAddJointPositions(builder, jointPositions)
def SkeletalPlayerWireStartJointPositionsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartJointPositionsVector(builder, numElems):
    return SkeletalPlayerWireStartJointPositionsVector(builder, numElems)
def SkeletalPlayerWireAddJointIds(builder, jointIds): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(jointIds), 0)
def AddJointIds(builder, jointIds):
    return SkeletalPlayerWireAddJointIds(builder, jointIds)
def SkeletalPlayerWireStartJointIdsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartJointIdsVector(builder, numElems):
    return SkeletalPlayerWireStartJointIdsVector(builder, numElems)
def SkeletalPlayerWireAddPlayerId(builder, playerId): builder.PrependUint32Slot(4, playerId, 0)
def AddPlayerId(builder, playerId):
    return SkeletalPlayerWireAddPlayerId(builder, playerId)
def SkeletalPlayerWireAddJerseyNumber(builder, jerseyNumber): builder.PrependUint32Slot(5, jerseyNumber, 0)
def AddJerseyNumber(builder, jerseyNumber):
    return SkeletalPlayerWireAddJerseyNumber(builder, jerseyNumber)
def SkeletalPlayerWireAddRoleId(builder, roleId): builder.PrependUint32Slot(6, roleId, 0)
def AddRoleId(builder, roleId):
    return SkeletalPlayerWireAddRoleId(builder, roleId)
def SkeletalPlayerWireEnd(builder): return builder.EndObject()
def End(builder):
    return SkeletalPlayerWireEnd(builder)