# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StatusEventDataWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StatusEventDataWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStatusEventDataWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StatusEventDataWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StatusEventDataWire
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def StatusEventDataWireStart(builder): builder.StartObject(1)
def Start(builder):
    return StatusEventDataWireStart(builder)
def StatusEventDataWireAddStatus(builder, status): builder.PrependInt8Slot(0, status, 0)
def AddStatus(builder, status):
    return StatusEventDataWireAddStatus(builder, status)
def StatusEventDataWireEnd(builder): return builder.EndObject()
def End(builder):
    return StatusEventDataWireEnd(builder)