# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TeamScoreEventDataWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TeamScoreEventDataWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTeamScoreEventDataWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TeamScoreEventDataWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TeamScoreEventDataWire
    def Speed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # TeamScoreEventDataWire
    def Angle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # TeamScoreEventDataWire
    def Direction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def TeamScoreEventDataWireStart(builder): builder.StartObject(3)
def Start(builder):
    return TeamScoreEventDataWireStart(builder)
def TeamScoreEventDataWireAddSpeed(builder, speed): builder.PrependFloat32Slot(0, speed, 0.0)
def AddSpeed(builder, speed):
    return TeamScoreEventDataWireAddSpeed(builder, speed)
def TeamScoreEventDataWireAddAngle(builder, angle): builder.PrependFloat32Slot(1, angle, 0.0)
def AddAngle(builder, angle):
    return TeamScoreEventDataWireAddAngle(builder, angle)
def TeamScoreEventDataWireAddDirection(builder, direction): builder.PrependFloat32Slot(2, direction, 0.0)
def AddDirection(builder, direction):
    return TeamScoreEventDataWireAddDirection(builder, direction)
def TeamScoreEventDataWireEnd(builder): return builder.EndObject()
def End(builder):
    return TeamScoreEventDataWireEnd(builder)