# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TrackingDataWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrackingDataWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTrackingDataWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TrackingDataWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TrackingDataWire
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TrackingDataWire
    def Frames(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MLB.TrackingFrameWire import TrackingFrameWire
            obj = TrackingFrameWire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrackingDataWire
    def FramesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TrackingDataWire
    def FramesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # TrackingDataWire
    def Limits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from MLB.LimitsWire import LimitsWire
            obj = LimitsWire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrackingDataWire
    def EventKeyFrame(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MLB.GameEventWire import GameEventWire
            obj = GameEventWire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrackingDataWire
    def EventKeyFrameLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TrackingDataWire
    def EventKeyFrameIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def TrackingDataWireStart(builder): builder.StartObject(4)
def Start(builder):
    return TrackingDataWireStart(builder)
def TrackingDataWireAddVersion(builder, version): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(version), 0)
def AddVersion(builder, version):
    return TrackingDataWireAddVersion(builder, version)
def TrackingDataWireAddFrames(builder, frames): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(frames), 0)
def AddFrames(builder, frames):
    return TrackingDataWireAddFrames(builder, frames)
def TrackingDataWireStartFramesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartFramesVector(builder, numElems):
    return TrackingDataWireStartFramesVector(builder, numElems)
def TrackingDataWireAddLimits(builder, limits): builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(limits), 0)
def AddLimits(builder, limits):
    return TrackingDataWireAddLimits(builder, limits)
def TrackingDataWireAddEventKeyFrame(builder, eventKeyFrame): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(eventKeyFrame), 0)
def AddEventKeyFrame(builder, eventKeyFrame):
    return TrackingDataWireAddEventKeyFrame(builder, eventKeyFrame)
def TrackingDataWireStartEventKeyFrameVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartEventKeyFrameVector(builder, numElems):
    return TrackingDataWireStartEventKeyFrameVector(builder, numElems)
def TrackingDataWireEnd(builder): return builder.EndObject()
def End(builder):
    return TrackingDataWireEnd(builder)