# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TrackingBatPositionWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrackingBatPositionWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTrackingBatPositionWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TrackingBatPositionWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TrackingBatPositionWire
    def HeadPosition(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from MLB.Vec3Wire import Vec3Wire
            obj = Vec3Wire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrackingBatPositionWire
    def HandlePosition(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from MLB.Vec3Wire import Vec3Wire
            obj = Vec3Wire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def TrackingBatPositionWireStart(builder): builder.StartObject(2)
def Start(builder):
    return TrackingBatPositionWireStart(builder)
def TrackingBatPositionWireAddHeadPosition(builder, headPosition): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(headPosition), 0)
def AddHeadPosition(builder, headPosition):
    return TrackingBatPositionWireAddHeadPosition(builder, headPosition)
def TrackingBatPositionWireAddHandlePosition(builder, handlePosition): builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(handlePosition), 0)
def AddHandlePosition(builder, handlePosition):
    return TrackingBatPositionWireAddHandlePosition(builder, handlePosition)
def TrackingBatPositionWireEnd(builder): return builder.EndObject()
def End(builder):
    return TrackingBatPositionWireEnd(builder)