# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TrackedEventWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrackedEventWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTrackedEventWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TrackedEventWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TrackedEventWire
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TrackedEventWire
    def BatSide(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TrackedEventWire
    def PitchHand(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TrackedEventWire
    def AtBatNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # TrackedEventWire
    def PitchNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # TrackedEventWire
    def PickoffNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # TrackedEventWire
    def SzTop(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # TrackedEventWire
    def SzBot(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # TrackedEventWire
    def EventType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TrackedEventWire
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # TrackedEventWire
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # TrackedEventWire
    def Z(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # TrackedEventWire
    def Position(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # TrackedEventWire
    def EventTypeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def TrackedEventWireStart(builder): builder.StartObject(14)
def Start(builder):
    return TrackedEventWireStart(builder)
def TrackedEventWireAddTimestamp(builder, timestamp): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)
def AddTimestamp(builder, timestamp):
    return TrackedEventWireAddTimestamp(builder, timestamp)
def TrackedEventWireAddBatSide(builder, batSide): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(batSide), 0)
def AddBatSide(builder, batSide):
    return TrackedEventWireAddBatSide(builder, batSide)
def TrackedEventWireAddPitchHand(builder, pitchHand): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(pitchHand), 0)
def AddPitchHand(builder, pitchHand):
    return TrackedEventWireAddPitchHand(builder, pitchHand)
def TrackedEventWireAddAtBatNumber(builder, atBatNumber): builder.PrependUint16Slot(3, atBatNumber, 0)
def AddAtBatNumber(builder, atBatNumber):
    return TrackedEventWireAddAtBatNumber(builder, atBatNumber)
def TrackedEventWireAddPitchNumber(builder, pitchNumber): builder.PrependUint16Slot(4, pitchNumber, 0)
def AddPitchNumber(builder, pitchNumber):
    return TrackedEventWireAddPitchNumber(builder, pitchNumber)
def TrackedEventWireAddPickoffNumber(builder, pickoffNumber): builder.PrependUint16Slot(5, pickoffNumber, 0)
def AddPickoffNumber(builder, pickoffNumber):
    return TrackedEventWireAddPickoffNumber(builder, pickoffNumber)
def TrackedEventWireAddSzTop(builder, szTop): builder.PrependFloat32Slot(6, szTop, 0.0)
def AddSzTop(builder, szTop):
    return TrackedEventWireAddSzTop(builder, szTop)
def TrackedEventWireAddSzBot(builder, szBot): builder.PrependFloat32Slot(7, szBot, 0.0)
def AddSzBot(builder, szBot):
    return TrackedEventWireAddSzBot(builder, szBot)
def TrackedEventWireAddEventType(builder, eventType): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(eventType), 0)
def AddEventType(builder, eventType):
    return TrackedEventWireAddEventType(builder, eventType)
def TrackedEventWireAddX(builder, x): builder.PrependFloat32Slot(9, x, 0.0)
def AddX(builder, x):
    return TrackedEventWireAddX(builder, x)
def TrackedEventWireAddY(builder, y): builder.PrependFloat32Slot(10, y, 0.0)
def AddY(builder, y):
    return TrackedEventWireAddY(builder, y)
def TrackedEventWireAddZ(builder, z): builder.PrependFloat32Slot(11, z, 0.0)
def AddZ(builder, z):
    return TrackedEventWireAddZ(builder, z)
def TrackedEventWireAddPosition(builder, position): builder.PrependUint16Slot(12, position, 0)
def AddPosition(builder, position):
    return TrackedEventWireAddPosition(builder, position)
def TrackedEventWireAddEventTypeId(builder, eventTypeId): builder.PrependInt8Slot(13, eventTypeId, 0)
def AddEventTypeId(builder, eventTypeId):
    return TrackedEventWireAddEventTypeId(builder, eventTypeId)
def TrackedEventWireEnd(builder): return builder.EndObject()
def End(builder):
    return TrackedEventWireEnd(builder)