# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MLB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TrackingFrameWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrackingFrameWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTrackingFrameWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TrackingFrameWire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TrackingFrameWire
    def ActorPoses(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MLB.ActorPoseWire import ActorPoseWire
            obj = ActorPoseWire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrackingFrameWire
    def ActorPosesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TrackingFrameWire
    def ActorPosesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # TrackingFrameWire
    def BallPosition(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from MLB.Vec3Wire import Vec3Wire
            obj = Vec3Wire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrackingFrameWire
    def GameEvents(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MLB.GameEventWire import GameEventWire
            obj = GameEventWire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrackingFrameWire
    def GameEventsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TrackingFrameWire
    def GameEventsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # TrackingFrameWire
    def TrackedEvents(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MLB.TrackedEventWire import TrackedEventWire
            obj = TrackedEventWire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrackingFrameWire
    def TrackedEventsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TrackingFrameWire
    def TrackedEventsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # TrackingFrameWire
    def InferredBat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MLB.TrackingBatPositionWire import TrackingBatPositionWire
            obj = TrackingBatPositionWire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrackingFrameWire
    def BallPolynomials(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MLB.BallPolynomialWire import BallPolynomialWire
            obj = BallPolynomialWire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrackingFrameWire
    def BallPolynomialsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TrackingFrameWire
    def BallPolynomialsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # TrackingFrameWire
    def RawJoints(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MLB.SkeletalPlayerWire import SkeletalPlayerWire
            obj = SkeletalPlayerWire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TrackingFrameWire
    def RawJointsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TrackingFrameWire
    def RawJointsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # TrackingFrameWire
    def Num(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # TrackingFrameWire
    def Time(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TrackingFrameWire
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TrackingFrameWire
    def IsGap(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TrackingFrameWire
    def GapDuration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def TrackingFrameWireStart(builder): builder.StartObject(12)
def Start(builder):
    return TrackingFrameWireStart(builder)
def TrackingFrameWireAddActorPoses(builder, actorPoses): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(actorPoses), 0)
def AddActorPoses(builder, actorPoses):
    return TrackingFrameWireAddActorPoses(builder, actorPoses)
def TrackingFrameWireStartActorPosesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartActorPosesVector(builder, numElems):
    return TrackingFrameWireStartActorPosesVector(builder, numElems)
def TrackingFrameWireAddBallPosition(builder, ballPosition): builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(ballPosition), 0)
def AddBallPosition(builder, ballPosition):
    return TrackingFrameWireAddBallPosition(builder, ballPosition)
def TrackingFrameWireAddGameEvents(builder, gameEvents): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(gameEvents), 0)
def AddGameEvents(builder, gameEvents):
    return TrackingFrameWireAddGameEvents(builder, gameEvents)
def TrackingFrameWireStartGameEventsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartGameEventsVector(builder, numElems):
    return TrackingFrameWireStartGameEventsVector(builder, numElems)
def TrackingFrameWireAddTrackedEvents(builder, trackedEvents): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(trackedEvents), 0)
def AddTrackedEvents(builder, trackedEvents):
    return TrackingFrameWireAddTrackedEvents(builder, trackedEvents)
def TrackingFrameWireStartTrackedEventsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartTrackedEventsVector(builder, numElems):
    return TrackingFrameWireStartTrackedEventsVector(builder, numElems)
def TrackingFrameWireAddInferredBat(builder, inferredBat): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(inferredBat), 0)
def AddInferredBat(builder, inferredBat):
    return TrackingFrameWireAddInferredBat(builder, inferredBat)
def TrackingFrameWireAddBallPolynomials(builder, ballPolynomials): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(ballPolynomials), 0)
def AddBallPolynomials(builder, ballPolynomials):
    return TrackingFrameWireAddBallPolynomials(builder, ballPolynomials)
def TrackingFrameWireStartBallPolynomialsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartBallPolynomialsVector(builder, numElems):
    return TrackingFrameWireStartBallPolynomialsVector(builder, numElems)
def TrackingFrameWireAddRawJoints(builder, rawJoints): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(rawJoints), 0)
def AddRawJoints(builder, rawJoints):
    return TrackingFrameWireAddRawJoints(builder, rawJoints)
def TrackingFrameWireStartRawJointsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartRawJointsVector(builder, numElems):
    return TrackingFrameWireStartRawJointsVector(builder, numElems)
def TrackingFrameWireAddNum(builder, num): builder.PrependUint32Slot(7, num, 0)
def AddNum(builder, num):
    return TrackingFrameWireAddNum(builder, num)
def TrackingFrameWireAddTime(builder, time): builder.PrependFloat64Slot(8, time, 0.0)
def AddTime(builder, time):
    return TrackingFrameWireAddTime(builder, time)
def TrackingFrameWireAddTimestamp(builder, timestamp): builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)
def AddTimestamp(builder, timestamp):
    return TrackingFrameWireAddTimestamp(builder, timestamp)
def TrackingFrameWireAddIsGap(builder, isGap): builder.PrependBoolSlot(10, isGap, 0)
def AddIsGap(builder, isGap):
    return TrackingFrameWireAddIsGap(builder, isGap)
def TrackingFrameWireAddGapDuration(builder, gapDuration): builder.PrependFloat64Slot(11, gapDuration, 0.0)
def AddGapDuration(builder, gapDuration):
    return TrackingFrameWireAddGapDuration(builder, gapDuration)
def TrackingFrameWireEnd(builder): return builder.EndObject()
def End(builder):
    return TrackingFrameWireEnd(builder)